export type LanguagesYaml = Record<
  string,
  {
    color?: string;
    aliases?: string[];
  }
>;

export const COLOR_YAML_LOCATION =
  "https://raw.githubusercontent.com/github-linguist/linguist/refs/heads/main/lib/linguist/languages.yml";

export const DISCLAIMER =
  "This file is auto-generated by gather.ts. Do not edit directly. See THIRD_PARTY_NOTICES for license information.";

export const OUTPUT_PATH = "src/languages.json";
