import fs from "node:fs/promises";
import { parse } from "yaml";

type LanguagesYaml = Record<
  string,
  {
    color?: string;
  }
>;

const COLOR_YAML_LOCATION =
  "https://raw.githubusercontent.com/github-linguist/linguist/refs/heads/main/lib/linguist/languages.yml";

const DISCLAIMER =
  "This file is auto-generated by gather.ts. Do not edit directly. See THIRD_PARTY_NOTICES for license information.";

const getYaml = async (): Promise<LanguagesYaml> => {
  const yamlRequest = await fetch(COLOR_YAML_LOCATION);

  if (!yamlRequest.ok) {
    throw new Error(
      `Failed to fetch YAML data: ${yamlRequest.status} ${yamlRequest.statusText}`,
    );
  }

  const yamlRaw = await yamlRequest.text();

  return parse(yamlRaw);
};

const convertYamlToLanguageData = (
  yaml: LanguagesYaml,
): Record<string, string> =>
  Object.keys(yaml).reduce(
    (acc, lang) => {
      const color = yaml[lang].color;

      if (color) {
        acc[lang.toLowerCase()] = color;
      }

      return acc;
    },
    {} as Record<string, string>,
  );

const rawLanguages = await getYaml();
const convertedLanguages = convertYamlToLanguageData(rawLanguages);

await fs
  .writeFile(
    "src/languages.json",
    JSON.stringify({ _disclaimer: DISCLAIMER, ...convertedLanguages }),
  )
  .catch((err) => {
    console.error("Failed to write languages.json:", err);
  });
